
//Auth Action Types

const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
const CLEAR_AUTH = 'CLEAR_AUTH';
const AUTH_REQUEST = 'AUTH_REQUEST';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_ERROR = 'AUTH_ERROR';
const SET_DIALOG = 'SET_DIALOG';

//Story Action Types

const STORY_REQUEST = 'STORY_REQUEST';
const STORY_SUCCESS = 'STORY_SUCCESS';
const STORY_ERROR = 'STORY_ERROR';
const SET_STORY = 'SET_STORY';
const EDIT_STORY = 'EDIT_STORY';
const ADD_STORY = 'ADD_STORY';
const SEARCH_STORY = 'SEARCH_STORY';

export {
	SET_AUTH_TOKEN,
	CLEAR_AUTH,
	AUTH_REQUEST,
	AUTH_SUCCESS,
	AUTH_ERROR,
	SET_DIALOG,
	STORY_REQUEST,
	STORY_SUCCESS,
	STORY_ERROR,
	SET_STORY,
	EDIT_STORY,
	ADD_STORY,
	SEARCH_STORY,
};
